### ISSUE TITLE
several small fixes/changes

### ISSUE THREAD

**Issue by danielnaber** [languagetooler-gmbh/languagetool-website-2018#1]
- [x] I've added a new section below the browser section called "Desktop version for offline use": its design should be like the browser section (font, colors, button style)
- [x] After that, please add a third section of the same style below, it will be for Google Docs (already added to the "Add-ons" menu)
- [x] The "(?)" icons in the pricing table are missing, you can hover over them to get more details - see current languagetoolplus.com
- [x] please center the ad (the white block I have added directly below the main text area)
- [x] /legal/terms and other sub pages: more vertical spacing between content and header and content and footer
- [x] Subscribe for the latest updates: open popup with email field -> take design from the lower left corner of the page but also make it work by using the code from current https://languagetool.org/ in the lower right corner
- [x] make the table sorting on /languages work again like on https://languagetool.org/languages/
- [x] make sure the "content page" font, e.g. on /issues, matches the original design at zeplin

**Comment by neprev** [comment]
@danielnaber please check
