### ISSUE TITLE
/team looks broken on mobile

### ISSUE THREAD

**Issue by danielnaber** [languagetooler-gmbh/languagetool-website-2018#13]
The multi-column approach used there doesn't seem to be mobile compatible.

**Comment by neprev** [comment]
@danielnaber please check

**Comment by danielnaber** [comment]
Actually, on Chrome/Android it is still broken:
![screenshot_2018-04-20-08-40-06](https://user-images.githubusercontent.com/857004/39034486-ce194bb4-4476-11e8-81ea-db5a832bb05f.png)

**Comment by neprev** [comment]
@danielnaber do you watch production?

**Comment by danielnaber** [comment]
Yes, I look at https://languagetool.org/team. This only happens on mobile (testing with Moto G), making the browser window less wide on desktop works okay.

**Comment by neprev** [comment]
@danielnaber that's how it looks for me. Can you please try to clear the cache on mobile browser
![image 2018-04-20 12 56 28](https://user-images.githubusercontent.com/28347933/39034989-3de8bf42-449a-11e8-8977-db19f4569fb7.jpg)

**Comment by danielnaber** [comment]
Was indeed a cache issue, sorry.
