### ISSUE TITLE
menu in front in fullscreen mode

### ISSUE THREAD

**Issue by danielnaber** [languagetooler-gmbh/languagetool-website-2018#2]
Hover with the mouse and the menu will appear, it shouldn't in fullscreen mode.

![menu-overlay](https://user-images.githubusercontent.com/857004/38360586-e04783bc-38ca-11e8-9d74-5de5906d7f34.png)

**Comment by neprev** [comment]
@danielnaber please check

**Comment by danielnaber** [comment]
Thanks!
