### ISSUE TITLE
menu needs to work on all pages

### ISSUE THREAD

**Issue by danielnaber** [languagetooler-gmbh/languagetool-website-2018#4]
The add-ons menu needs to scroll down when the user is on a "full" page that has all the content (/, /de, /fr etc). On other pages, it needs to link `/#anchor` instead so it goes to the section on the main page.

**Comment by neprev** [comment]
@danielnaber please check

**Comment by danielnaber** [comment]
This doesn't work properly, as now when you're on /de and click the menu, you end up on the homepage - but the /de page has its own section for the items in the menu, so the page should scroll down to that section.

**Comment by neprev** [comment]
@danielnaber please check
