### ISSUE TITLE
"Please specify: languagetool_rpc_url"

### ISSUE THREAD

**Issue by danielnaber** [languagetooler-gmbh/languagetool-website-2018#8]
![rpc](https://user-images.githubusercontent.com/857004/38766443-92d07814-3fd2-11e8-8f54-edaa9cdb3b1e.png)

This sometimes happens - timing issue?

**Comment by neprev** [comment]
@danielnaber 
<img width="287" alt="screen shot 2018-04-18 at 23 01 53" src="https://user-images.githubusercontent.com/28347933/38946965-dd2462bc-435c-11e8-806b-95eed4023b67.png">
<img width="663" alt="screen shot 2018-04-18 at 23 02 11" src="https://user-images.githubusercontent.com/28347933/38946967-e110e1fc-435c-11e8-90d8-bd33cb4237db.png">
This happends randomly in 10% cases. I have no idea why this code is needed. You know better. What do you need to do here?
